name: publish-reports
on: [push]
jobs:
  publish-example-cucumber-report:
    runs-on: ubuntu-latest
    steps:
      - uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'example/cucumber.html'
