name: publish-reports
on: [push]
jobs:
  publish-example-cucumber-report:
    runs-on: ubuntu-latest
    steps:
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: example/cucumber.*

