name: publish-reports
on: [push]
jobs:
  publish-example-cucumber-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Show contents
        run:
            find . -type f -ls

      - name: Generate Preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'example/cucumber.html'

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: example/cucumber.html

