name: publish-reports
on: [push]
jobs:
  publish-example-cucumber-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: SIMULATE A BUILD
        run: |
            mkdir target
            cp example/* target/

      - name: Show contents
        run: |
            find . -type f -ls

      - name: CUCUMBER Annotations Action
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"

      # DOES NOT APPEAR TO WORK FOR BUILD OUTPUT FILES
      - name: Generate Preview
        uses: pavi2410/html-preview-action@v2
        id: html_preview
        with:
          html_file: 'target/cucumber.html'

      - name: REPORT Preview URL
        run: |
            echo "PREVIEW RERPORT URL: ${{ steps.html_preview.outputs.url }}"

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber.html

